/**
 * enrichment-taxonomy.ts — D-118 Phase 1: Operation Classification
 *
 * Canonical taxonomy for all model operations. Separates:
 *   - Enrichments: modify the structural scaffold (Invariant 2, Structural layer)
 *   - Diagnostics: assess without modifying (Invariant 2, Diagnostic/Interpretive layers)
 *
 * This module is the single source of truth for operation metadata, dependency
 * declarations, readiness gates, and the recommended journey computation.
 *
 * @see docs/DECISIONS.md D-118
 * @see docs/DESIGN-PRINCIPLES.md Invariant 2: Layer Separation in Reasoning
 */

// ─── External Input Artefacts ────────────────────────────────────────────────

/**
 * External Input Artefacts are structured documents that become inputs to
 * enrichments and diagnostics. They can be:
 *
 *   - **Provided**: the user uploads or enters their own content (e.g., a real
 *     SWOT analysis, a client's risk register, a regulatory framework document).
 *
 *   - **Generated**: the tool creates a baseline from existing model content
 *     (e.g., generating a Risk Register from friction analysis, a Metrics Library
 *     from industry benchmarks, a Maturity Assessment from PPIT depth analysis).
 *
 * The provenance distinction matters because:
 *   1. Provided inputs carry higher confidence (real-world evidence).
 *   2. Generated inputs carry a scaffold hash — they can go stale.
 *   3. The NBA engine weights provided > generated (+5 vs +3 bonus).
 *   4. Downstream diagnostics propagate confidence from their inputs,
 *      creating an audit trail for board-facing outputs.
 *
 * External inputs are stored at project level (not scaffold level) because
 * they represent organisational context that persists across scaffold versions.
 *
 * @see D-118 Phase 1, FA SPAR Review (31 Mar 2026) — provenance + confidence propagation
 */
export type ExternalInputType =
  | "swot"                   // SWOT analysis — Minimum Viable Input for most diagnostics
  | "strategic-plan"         // Goals, strategies, objectives, initiatives
  | "initiative-charter"     // Scope, objectives, success criteria for a specific initiative
  | "risk-register"          // Existing organisational risk register
  | "regulatory-framework"   // Applicable regulations, controls, compliance requirements
  | "metrics-library"        // Industry/organisational benchmark metrics with quartile targets
  | "maturity-assessment"    // Existing maturity assessment from another framework
  | "custom";                // User-defined structured input

/**
 * Provenance distinguishes user-supplied inputs from AI-generated baselines.
 * This affects confidence weighting, staleness tracking, and NBA scoring.
 */
export type InputProvenance = "provided" | "generated";

/**
 * Which external input types can be generated by the tool from model content.
 * Others (strategic-plan, initiative-charter, regulatory-framework) must be
 * provided by the user — they represent organisational intent or external
 * constraints that cannot be inferred from the operating model.
 */
export const GENERABLE_INPUT_TYPES: ExternalInputType[] = [
  "risk-register",        // Generated from friction analysis findings
  "metrics-library",      // Generated from industry + VS type benchmarks
  "maturity-assessment",  // Generated from PPIT depth and scaffold completeness
];

export interface ExternalInputArtefact {
  /** Unique ID */
  id: string;
  /** What type of external input this is */
  type: ExternalInputType;
  /** User-supplied label */
  label: string;
  /** ISO timestamp of when this was created or uploaded */
  providedAt: string;
  /** Confidence level for this input overall */
  confidence: "accurate" | "informed" | "estimate" | "unknown";
  /** The structured content (shape depends on type) */
  payload: unknown;
  /** Which operations consume this input */
  consumedBy: string[];

  // ── Provenance tracking ──

  /** Whether this input was provided by the user or generated by the tool */
  provenance: InputProvenance;

  // ── Generation tracking (only present when provenance === "generated") ──

  /**
   * The operation or model state that produced this input.
   * E.g., "friction" for a risk register generated from friction analysis.
   * Only set when provenance === "generated".
   */
  generatedFrom?: string;
  /**
   * Scaffold content hash at the time this input was generated.
   * Used for staleness detection on generated inputs.
   * Only set when provenance === "generated".
   */
  generatedAtScaffoldHash?: string;
}

/**
 * Collection of all external input artefacts for a project.
 * Keyed by artefact ID.
 */
export type ExternalInputStore = Record<string, ExternalInputArtefact>;

// ─── Operation Type ──────────────────────────────────────────────────────────

/**
 * An Enrichment modifies the canonical scaffold JSON.
 * A Diagnostic produces overlay artefacts that reference the scaffold by hash.
 */
export type OperationType = "enrichment" | "diagnostic";

/**
 * Ontological layer per Invariant 2.
 *   - structural: scaffold content (only enrichments)
 *   - diagnostic: friction observations, maturity scores, dependency maps
 *   - interpretive: binding constraints, gap registers, risk registers
 */
export type OntologicalLayer = "structural" | "diagnostic" | "interpretive";

// ─── Model Readiness ─────────────────────────────────────────────────────────

/**
 * Progressive readiness states derived from scaffold content.
 * Never stored — always computed by `computeReadiness()`.
 */
export type ReadinessState =
  | "skeleton"   // Pass A+B complete. Stages, capabilities, roles, IOs as IDs/names.
  | "grounded"   // PPIT mapped. Activities have capabilityPPIT decompositions.
  | "detailed"   // Activity flow DAGs derived. Cross-maps and metrics populated.
  | "assessed"   // Diagnostics applied. Friction heatmap, maturity scores exist.
  | "governed";  // Gap register and risk register complete.

/** Ordered progression — index is the numeric level (0–4). */
export const READINESS_ORDER: ReadinessState[] = [
  "skeleton",
  "grounded",
  "detailed",
  "assessed",
  "governed",
];

export const READINESS_LABELS: Record<ReadinessState, string> = {
  skeleton: "Skeleton",
  grounded: "Grounded",
  detailed: "Detailed",
  assessed: "Assessed",
  governed: "Governed",
};

export const READINESS_DESCRIPTIONS: Record<ReadinessState, string> = {
  skeleton:
    "Initial scaffold from discovery. Stages, capabilities, roles, and IOs exist as IDs and names. No depth below top-level elements.",
  grounded:
    "PPIT mapped. Each activity×capability pair has People, Process, Information, Technology decomposition. Model has operational depth.",
  detailed:
    "Activity flow DAGs derived. Sub-activity sequences, decision gates, and handoffs documented. Cross-maps and metrics populated.",
  assessed:
    "Diagnostics applied. Friction heatmap, maturity scores, and metrics baselines exist as overlay artefacts. Model has analytical depth.",
  governed:
    "Gap register and risk register complete. Full current-state picture with target-state comparison and risk overlay.",
};

// ─── Dependency Types ────────────────────────────────────────────────────────

/**
 * Required: blocks execution (soft block — warning with override).
 * Recommended: advisory message, user can proceed.
 */
export type DependencyType = "required" | "recommended";

export interface OperationDependency {
  /** ID of the operation this depends on */
  operationId: string;
  /** Whether this is a hard prerequisite or advisory */
  type: DependencyType;
  /** Human-readable reason for the dependency */
  reason: string;
}

// ─── Operation Definition ────────────────────────────────────────────────────

/**
 * Canonical definition of a model operation. This replaces the ad-hoc
 * EnrichmentCardDef for taxonomy and dependency purposes, while EnrichmentCardDef
 * remains for UI-specific fields (icon, description, contentHint, customUI).
 */
export interface OperationDefinition {
  /** Unique ID matching the EnrichmentCardDef.id */
  id: string;
  /** Display label */
  label: string;
  /** Enrichment or Diagnostic */
  operationType: OperationType;
  /** Which ontological layer this operates in */
  layer: OntologicalLayer;
  /** Minimum readiness state required to run */
  readinessGate: ReadinessState;
  /** What readiness state the model reaches after this completes (enrichments only) */
  advancesTo?: ReadinessState;
  /** Declared dependencies */
  dependencies: OperationDependency[];
  /** Whether the operation is currently implemented */
  implemented: boolean;
  /** Where this operation writes its output */
  outputTarget: "scaffold" | "diagnostic-artefact" | "card-registry";
  /**
   * External input artefact types this operation can consume.
   * When these are present in the project, the operation uses them
   * to produce richer, more grounded output.
   */
  externalInputs?: ExternalInputType[];
}

// ─── Operation Registry ──────────────────────────────────────────────────────

/**
 * Single source of truth for all operation metadata.
 * Order reflects the recommended journey (foundation → depth → diagnostics).
 */
export const OPERATION_REGISTRY: OperationDefinition[] = [
  // ── Enrichments (modify scaffold) ──────────────────────────────────────

  {
    id: "ppit",
    label: "Map PPIT",
    operationType: "enrichment",
    layer: "structural",
    readinessGate: "skeleton",
    advancesTo: "grounded",
    dependencies: [],
    implemented: true,
    outputTarget: "scaffold",
  },
  {
    id: "cards",
    label: "Generate Concept & Policy Cards",
    operationType: "enrichment",
    layer: "structural",
    readinessGate: "skeleton",
    advancesTo: "grounded",
    dependencies: [],
    implemented: true,
    outputTarget: "card-registry",
  },
  {
    id: "subactivities",
    label: "Derive Activity Flows",
    operationType: "enrichment",
    layer: "structural",
    readinessGate: "grounded",
    advancesTo: "detailed",
    dependencies: [
      {
        operationId: "ppit",
        type: "required",
        reason:
          "Activity Flows are built from capabilityPPIT sub-activities. Without PPIT data, DAGs are generated from stage names alone — significantly less accurate.",
      },
    ],
    implemented: true,
    outputTarget: "scaffold",
  },
  {
    id: "cross-mapping",
    label: "Cross-Map Relationships",
    operationType: "enrichment",
    layer: "structural",
    readinessGate: "grounded",
    advancesTo: "detailed",
    dependencies: [
      {
        operationId: "ppit",
        type: "recommended",
        reason:
          "Cross-maps are richer when PPIT data provides role, info, and tech elements to map between.",
      },
    ],
    implemented: true,
    outputTarget: "scaffold",
  },
  {
    id: "metrics",
    label: "Generate Performance Metrics",
    operationType: "enrichment",
    layer: "structural",
    readinessGate: "grounded",
    advancesTo: "detailed",
    dependencies: [
      {
        operationId: "ppit",
        type: "recommended",
        reason:
          "Metrics aligned to PPIT decompositions are more operationally meaningful.",
      },
    ],
    implemented: false,
    outputTarget: "scaffold",
    externalInputs: ["metrics-library"],
  },

  // ── Diagnostics (assess without modifying scaffold) ────────────────────

  {
    id: "friction",
    label: "Assess Friction & Bottlenecks",
    operationType: "diagnostic",
    layer: "diagnostic",
    readinessGate: "grounded",
    dependencies: [
      {
        operationId: "ppit",
        type: "recommended",
        reason:
          "Friction analysis is more precise when PPIT decompositions identify specific people, process, information, and technology touchpoints.",
      },
      {
        operationId: "subactivities",
        type: "recommended",
        reason:
          "Activity flow DAGs reveal handoff points and decision gates where friction commonly occurs.",
      },
    ],
    implemented: true,
    outputTarget: "diagnostic-artefact",
    externalInputs: ["swot", "metrics-library"],
  },
  {
    id: "dependencies",
    label: "Map Cross-Stream Dependencies",
    operationType: "diagnostic",
    layer: "diagnostic",
    readinessGate: "detailed",
    dependencies: [
      {
        operationId: "ppit",
        type: "required",
        reason:
          "Cross-stream analysis requires PPIT data to identify shared capabilities, systems, and teams.",
      },
      {
        operationId: "cross-mapping",
        type: "recommended",
        reason:
          "Existing cross-maps provide explicit relationship data to validate dependency findings.",
      },
    ],
    implemented: false,
    outputTarget: "diagnostic-artefact",
  },
  {
    id: "maturity",
    label: "Capability Maturity Assessment",
    operationType: "diagnostic",
    layer: "diagnostic",
    readinessGate: "detailed",
    dependencies: [
      {
        operationId: "ppit",
        type: "required",
        reason:
          "Maturity assessment evaluates process standardisation, automation, measurement — all PPIT dimensions.",
      },
      {
        operationId: "metrics",
        type: "recommended",
        reason:
          "Existing metrics provide baseline measurement data for maturity scoring.",
      },
    ],
    implemented: false,
    outputTarget: "diagnostic-artefact",
    externalInputs: ["swot", "maturity-assessment"],
  },
  {
    id: "gap-analysis",
    label: "Current vs Target Gap Analysis",
    operationType: "diagnostic",
    layer: "interpretive",
    readinessGate: "assessed",
    dependencies: [
      {
        operationId: "maturity",
        type: "required",
        reason:
          "Gap analysis compares current maturity against target state — requires maturity baseline.",
      },
      {
        operationId: "metrics",
        type: "recommended",
        reason:
          "Performance metrics provide quantitative basis for gap identification.",
      },
    ],
    implemented: false,
    outputTarget: "diagnostic-artefact",
    externalInputs: ["swot", "strategic-plan", "initiative-charter"],
  },
  {
    id: "risk",
    label: "Operational Risk Assessment",
    operationType: "diagnostic",
    layer: "interpretive",
    readinessGate: "assessed",
    dependencies: [
      {
        operationId: "friction",
        type: "required",
        reason:
          "Risk assessment builds on identified friction points — friction patterns indicate areas of operational vulnerability.",
      },
      {
        operationId: "maturity",
        type: "recommended",
        reason:
          "Maturity scores help calibrate risk severity — low-maturity capabilities carry higher operational risk.",
      },
      {
        operationId: "dependencies",
        type: "recommended",
        reason:
          "Cross-stream dependencies identify blast radius — risks in shared capabilities propagate further.",
      },
    ],
    implemented: false,
    outputTarget: "diagnostic-artefact",
    externalInputs: ["swot", "risk-register"],
  },

  // ── Strategic & Compliance Diagnostics (CAPSICUM Strategic Purpose layer) ──

  {
    id: "strategic-alignment",
    label: "Strategic Alignment Assessment",
    operationType: "diagnostic",
    layer: "interpretive",
    readinessGate: "assessed",
    dependencies: [
      {
        operationId: "friction",
        type: "required",
        reason:
          "Strategic alignment evaluates whether friction patterns and capability gaps obstruct or support strategic objectives.",
      },
      {
        operationId: "maturity",
        type: "recommended",
        reason:
          "Maturity scores indicate which capabilities are ready to support strategic initiatives and which need uplift.",
      },
      {
        operationId: "gap-analysis",
        type: "recommended",
        reason:
          "Gap register provides the target-state comparison that strategic alignment scoring requires.",
      },
    ],
    implemented: false,
    outputTarget: "diagnostic-artefact",
    externalInputs: ["swot", "strategic-plan", "initiative-charter"],
  },
  {
    id: "initiative-impact",
    label: "Initiative Impact Analysis",
    operationType: "diagnostic",
    layer: "interpretive",
    readinessGate: "grounded",
    dependencies: [
      {
        operationId: "ppit",
        type: "required",
        reason:
          "Initiative impact requires PPIT decompositions to trace which people, processes, information, and technology are affected by the proposed scope of work.",
      },
      {
        operationId: "cross-mapping",
        type: "recommended",
        reason:
          "Cross-maps reveal indirect impacts — capabilities and systems not in the initiative scope but coupled to those that are.",
      },
    ],
    implemented: false,
    outputTarget: "diagnostic-artefact",
    externalInputs: ["swot", "initiative-charter"],
  },
  {
    id: "compliance",
    label: "Regulatory Compliance Assessment",
    operationType: "diagnostic",
    layer: "interpretive",
    readinessGate: "detailed",
    dependencies: [
      {
        operationId: "ppit",
        type: "required",
        reason:
          "Compliance assessment maps regulatory controls to capabilities, activities, and information assets — all PPIT elements.",
      },
      {
        operationId: "cards",
        type: "recommended",
        reason:
          "Policy Cards provide governance rules and control definitions that compliance assessment validates against regulatory requirements.",
      },
    ],
    implemented: false,
    outputTarget: "diagnostic-artefact",
    externalInputs: ["swot", "regulatory-framework"],
  },
];

// ─── Lookup Helpers ──────────────────────────────────────────────────────────

/** Map from operation ID to definition for O(1) lookup. */
export const OPERATIONS_BY_ID: Record<string, OperationDefinition> =
  Object.fromEntries(OPERATION_REGISTRY.map((op) => [op.id, op]));

/** All enrichment operations (modify scaffold). */
export const ENRICHMENT_OPS = OPERATION_REGISTRY.filter(
  (op) => op.operationType === "enrichment"
);

/** All diagnostic operations (assess without modifying). */
export const DIAGNOSTIC_OPS = OPERATION_REGISTRY.filter(
  (op) => op.operationType === "diagnostic"
);

// ─── Diagnostic Artefact Types ───────────────────────────────────────────────

/**
 * Confidence level for a diagnostic result, derived from the quality of its
 * inputs at the time it was run. This creates an audit trail:
 *
 *   - "high": all required inputs are Provided with "accurate" or "informed" confidence
 *   - "moderate": inputs present but some are Generated or have "estimate" confidence
 *   - "low": key inputs missing or mostly "estimate"/"unknown" confidence
 *   - "indicative": no external inputs used; result is purely model-inferred
 *
 * This propagates through to board-facing outputs — a Risk Assessment run with
 * only a guess-level SWOT will carry "low" confidence, signalling the need for
 * better input data rather than hiding the uncertainty.
 *
 * @see FA SPAR Review (31 Mar 2026) — Epistemic Integrity / Confidence Propagation
 */
export type DiagnosticConfidence = "high" | "moderate" | "low" | "indicative";

/**
 * Quantified staleness delta — tells the user exactly what changed since this
 * diagnostic was produced. Turns "Re-run" from a maintenance chore into a
 * curiosity trigger: "5 new capabilities added since this was run."
 *
 * @see FA SPAR Review (31 Mar 2026) — Staleness as Curiosity Trigger
 */
export interface StalenessDelta {
  /** Element counts at the time the diagnostic was produced */
  atProduction: Record<string, number>;
  /** Element counts in the current scaffold */
  atCurrent: Record<string, number>;
  /** Human-readable summary of what changed */
  summary: string;
}

/**
 * Base interface for all diagnostic artefacts.
 * Every diagnostic output must record which scaffold version it was derived from.
 * This enables staleness detection (D-118 non-negotiable #3).
 */
export interface DiagnosticArtefactBase {
  /** Which diagnostic operation produced this */
  diagnosticId: string;
  /** Content hash of the scaffold when this was produced */
  scaffoldHash: string;
  /** ISO timestamp of when this diagnostic was run */
  producedAt: string;
  /** Whether this artefact is stale (scaffold has changed since production) */
  stale: boolean;

  // ── Confidence propagation ──

  /**
   * Derived confidence based on the quality and provenance of inputs used.
   * Computed at diagnostic run time, never stored as user input.
   */
  derivedConfidence: DiagnosticConfidence;
  /**
   * Which external inputs were consumed by this diagnostic at run time.
   * Records both the input ID and its provenance+confidence at the time,
   * so the audit trail is frozen even if inputs are later updated.
   */
  inputSnapshot: Array<{
    inputId: string;
    inputType: ExternalInputType;
    provenance: InputProvenance;
    confidence: "accurate" | "informed" | "estimate" | "unknown";
  }>;

  // ── Staleness detail ──

  /**
   * When stale === true, this contains the quantified delta explaining
   * exactly what changed in the scaffold since this diagnostic was produced.
   * Computed on demand by comparing scaffold element counts.
   */
  stalenessDelta?: StalenessDelta;
}

/**
 * Friction diagnostic artefact — wraps existing HeatmapData.
 * The heatmap data itself is unchanged; we add provenance metadata.
 */
export interface FrictionDiagnosticArtefact extends DiagnosticArtefactBase {
  diagnosticId: "friction";
  /** The existing HeatmapData, keyed by value stream ID */
  heatmapsByVs: Record<string, unknown>;
}

/**
 * Generic diagnostic artefact for future diagnostics (maturity, dependencies, gap, risk).
 * Shape will be refined as each diagnostic is implemented.
 */
export interface GenericDiagnosticArtefact extends DiagnosticArtefactBase {
  diagnosticId: string;
  /** Diagnostic-specific payload */
  payload: unknown;
}

/** Union of all diagnostic artefact types */
export type DiagnosticArtefact =
  | FrictionDiagnosticArtefact
  | GenericDiagnosticArtefact;

/**
 * Collection of all diagnostic artefacts for a model.
 * Keyed by diagnostic operation ID.
 */
export type DiagnosticArtefactStore = Record<string, DiagnosticArtefact>;

// ─── Metrics Library Types ───────────────────────────────────────────────────

/**
 * A Metrics Library is a reference asset — curated performance measures
 * with industry benchmarks and quartile targets. Unlike other external inputs,
 * metrics libraries accumulate across projects and clients, forming an
 * organisational knowledge base.
 *
 * Metrics can be scoped to: industry, value stream type, value stream stage,
 * activity type, or capability domain. When present, the "Generate Performance
 * Metrics" enrichment uses the library to ground its output in real benchmarks
 * rather than pure LLM inference.
 */
export interface MetricDefinition {
  /** Unique ID */
  id: string;
  /** Metric name (e.g., "Average Cycle Time", "First Contact Resolution Rate") */
  name: string;
  /** What this metric measures */
  description: string;
  /** Unit of measurement (e.g., "hours", "percentage", "count per month") */
  unit: string;
  /** Measurement direction: higher-is-better or lower-is-better */
  polarity: "higher-is-better" | "lower-is-better";
  /** Scoping tags — where does this metric apply */
  scope: MetricScope;
  /** Quartile benchmarks (when available) */
  benchmarks?: MetricBenchmarks;
}

export interface MetricScope {
  /** Industry verticals this metric applies to (empty = universal) */
  industries?: string[];
  /** Value stream types (e.g., "customer-acquisition", "fulfilment") */
  valueStreamTypes?: string[];
  /** Stage types (e.g., "intake", "processing", "delivery") */
  stageTypes?: string[];
  /** Capability domains (e.g., L1/L2 capability labels) */
  capabilityDomains?: string[];
}

export interface MetricBenchmarks {
  /** Data source (e.g., "APQC 2025", "user-provided", "estimated") */
  source: string;
  /** Confidence level of the benchmarks */
  confidence: "accurate" | "informed" | "estimate" | "unknown";
  /** Quartile values — Q1 is bottom 25%, Q4 is top 25% */
  q1?: number;
  q2?: number; // median
  q3?: number;
  q4?: number;
  /** User's own current value for this metric */
  currentValue?: number;
  /** User's target value */
  targetValue?: number;
}

// ─── SWOT Analysis Types ─────────────────────────────────────────────────────

/**
 * A SWOT Analysis is the Minimum Viable Input for most diagnostics.
 *
 * Almost any stakeholder can produce a SWOT — even a rough gut-feel version
 * is enough to seed analytical context. Each item carries a confidence level
 * (how certain the author is) and a severity/impact score (how significant),
 * giving the system evidential grounding without requiring formal documents.
 *
 * SWOT items map naturally to diagnostic operations:
 *   - Strengths  → Capability Maturity (what we're good at)
 *   - Weaknesses → Friction Assessment, Gap Analysis (where we struggle)
 *   - Opportunities → Strategic Alignment, Initiative Impact (where to invest)
 *   - Threats → Risk Assessment, Compliance (what could hurt us)
 *
 * When no strategic plan, risk register, or other formal input exists,
 * a SWOT analysis is the recommended starting point. The NBA engine will
 * suggest providing one when diagnostics are available but no external
 * inputs have been supplied.
 */
export type SwotQuadrant = "strength" | "weakness" | "opportunity" | "threat";

export interface SwotItem {
  /** Unique ID */
  id: string;
  /** Which quadrant */
  quadrant: SwotQuadrant;
  /** Short title (e.g., "Strong digital fulfilment capability") */
  title: string;
  /** Longer description with context */
  description: string;
  /** How certain is the author about this item */
  confidence: "accurate" | "informed" | "estimate" | "unknown";
  /** Severity/impact on a 1–5 scale (1 = minor, 5 = critical) */
  severity: 1 | 2 | 3 | 4 | 5;
  /**
   * Optional scaffold element references — which capabilities, value streams,
   * activities, or roles does this item relate to? These allow the system to
   * anchor SWOT items to specific parts of the operating model.
   */
  relatedElementIds?: string[];
  /** Optional tags for categorisation (e.g., "technology", "regulatory", "people") */
  tags?: string[];
}

export interface SwotAnalysis {
  /** User-supplied label (e.g., "FY26 Strategic SWOT", "Quick Assessment") */
  label: string;
  /** ISO timestamp of when this was produced */
  producedAt: string;
  /** Overall confidence in the SWOT as a whole */
  overallConfidence: "accurate" | "informed" | "estimate" | "unknown";
  /** The items, grouped by quadrant for convenience */
  items: SwotItem[];
}

/** Helper: extract items by quadrant */
export function swotByQuadrant(swot: SwotAnalysis): Record<SwotQuadrant, SwotItem[]> {
  return {
    strength: swot.items.filter((i) => i.quadrant === "strength"),
    weakness: swot.items.filter((i) => i.quadrant === "weakness"),
    opportunity: swot.items.filter((i) => i.quadrant === "opportunity"),
    threat: swot.items.filter((i) => i.quadrant === "threat"),
  };
}

// ─── Confidence Propagation ─────────────────────────────────────────────────

/**
 * Compute the derived confidence for a diagnostic based on the external inputs
 * it consumed. This is called at diagnostic run time to freeze the confidence
 * into the artefact.
 *
 * Algorithm:
 *   1. No external inputs → "indicative" (purely model-inferred)
 *   2. All provided + accurate/informed → "high"
 *   3. Mix of provided and generated, or informed/estimate → "moderate"
 *   4. Mostly estimate/unknown → "low"
 */
export function computeDerivedConfidence(
  inputs: Array<{ provenance: InputProvenance; confidence: "accurate" | "informed" | "estimate" | "unknown" }>
): DiagnosticConfidence {
  if (inputs.length === 0) return "indicative";

  const weights: Record<string, number> = {
    accurate: 4,
    informed: 3,
    estimate: 2,
    unknown: 1,
  };
  const provenanceBonus: Record<InputProvenance, number> = {
    provided: 1,
    generated: 0,
  };

  let totalScore = 0;
  for (const input of inputs) {
    totalScore += weights[input.confidence] + provenanceBonus[input.provenance];
  }
  const avgScore = totalScore / inputs.length;

  // Thresholds: high ≥ 4, moderate ≥ 2.5, low ≥ 1.5, indicative below
  if (avgScore >= 4) return "high";
  if (avgScore >= 2.5) return "moderate";
  return "low";
}

// ─── Staleness Delta Computation ────────────────────────────────────────────

/**
 * Count scaffold elements by type for staleness delta comparison.
 */
export function countScaffoldElements(scaffold: any): Record<string, number> {
  const elements = scaffold?.elements ?? {};
  const counts: Record<string, number> = {};
  const keys = [
    "valueStreams", "activities", "capabilities", "roles",
    "informationObjects", "applicationFunctions", "controls",
    "metrics", "subActivityGraphs",
  ];
  for (const key of keys) {
    counts[key] = elements[key] ? Object.keys(elements[key]).length : 0;
  }
  return counts;
}

/**
 * Compute a human-readable staleness delta between the scaffold state when
 * a diagnostic was produced and the current scaffold state.
 *
 * Returns null if the scaffold hasn't changed in any meaningful way.
 */
export function computeStalenessDelta(
  atProduction: Record<string, number>,
  atCurrent: Record<string, number>
): StalenessDelta | null {
  const labels: Record<string, string> = {
    valueStreams: "value streams",
    activities: "stages",
    capabilities: "capabilities",
    roles: "roles",
    informationObjects: "information objects",
    applicationFunctions: "application functions",
    controls: "controls",
    metrics: "metrics",
    subActivityGraphs: "activity flow graphs",
  };

  const parts: string[] = [];
  for (const [key, label] of Object.entries(labels)) {
    const before = atProduction[key] ?? 0;
    const after = atCurrent[key] ?? 0;
    const diff = after - before;
    if (diff > 0) {
      parts.push(`${diff} new ${label}`);
    } else if (diff < 0) {
      parts.push(`${Math.abs(diff)} ${label} removed`);
    }
  }

  if (parts.length === 0) return null;

  return {
    atProduction,
    atCurrent,
    summary: `Model changed since this was run: ${parts.join(", ")}.`,
  };
}

// ─── Provenance Helpers ─────────────────────────────────────────────────────

/** Check whether an external input type can be AI-generated from model content. */
export function isGenerable(type: ExternalInputType): boolean {
  return GENERABLE_INPUT_TYPES.includes(type);
}

/** Human-readable labels for external input types. */
export const EXTERNAL_INPUT_LABELS: Record<ExternalInputType, string> = {
  swot: "SWOT Analysis",
  "strategic-plan": "Strategic Plan",
  "initiative-charter": "Initiative Charter",
  "risk-register": "Risk Register",
  "regulatory-framework": "Regulatory Framework",
  "metrics-library": "Metrics Library",
  "maturity-assessment": "Maturity Assessment",
  custom: "Custom Input",
};

/** Icons for external input types. */
export const EXTERNAL_INPUT_ICONS: Record<ExternalInputType, string> = {
  swot: "📋",
  "strategic-plan": "🎯",
  "initiative-charter": "📑",
  "risk-register": "⚠️",
  "regulatory-framework": "📏",
  "metrics-library": "📊",
  "maturity-assessment": "📈",
  custom: "📄",
};
